export const COUNTRIES = [
  {
    name: 'Afghanistan',
    code: 'AF',
    currency: 'AFN',
    nativeName: 'افغانستان',
    timezones: ['Asia/Kabul'],
  },
  {
    name: 'Aland Islands',
    code: 'AX',
    currency: 'EUR',
    nativeName: 'Åland',
    timezones: ['Europe/Mariehamn'],
  },
  {
    name: 'Albania',
    code: 'AL',
    currency: 'ALL',
    nativeName: 'Shqipëria',
    timezones: ['Europe/Tirane'],
  },
  {
    name: 'Algeria',
    code: 'DZ',
    currency: 'DZD',
    nativeName: 'الجزائر',
    timezones: ['Africa/Algiers'],
  },
  {
    name: 'American Samoa',
    code: 'AS',
    currency: 'USD',
    nativeName: 'American Samoa',
    timezones: ['Pacific/Pago_Pago'],
  },
  {
    name: 'Andorra',
    code: 'AD',
    currency: 'EUR',
    nativeName: 'Andorra',
    timezones: ['Europe/Andorra'],
  },
  {
    name: 'Angola',
    code: 'AO',
    currency: 'AOA',
    nativeName: 'Angola',
    timezones: ['Africa/Luanda'],
  },
  {
    name: 'Anguilla',
    code: 'AI',
    currency: 'XCD',
    nativeName: 'Anguilla',
    timezones: ['America/Anguilla'],
  },
  {
    name: 'Antarctica',
    code: 'AQ',
    currency: 'AAD',
    nativeName: 'Antarctica',
    timezones: [
      'Antarctica/Casey',
      'Antarctica/Davis',
      'Antarctica/DumontDUrville',
      'Antarctica/Mawson',
      'Antarctica/McMurdo',
      'Antarctica/Palmer',
      'Antarctica/Rothera',
      'Antarctica/Syowa',
      'Antarctica/Troll',
      'Antarctica/Vostok',
    ],
  },
  {
    name: 'Antigua And Barbuda',
    code: 'AG',
    currency: 'XCD',
    nativeName: 'Antigua and Barbuda',
    timezones: ['America/Antigua'],
  },
  {
    name: 'Argentina',
    code: 'AR',
    currency: 'ARS',
    nativeName: 'Argentina',
    timezones: [
      'America/Argentina/Buenos_Aires',
      'America/Argentina/Catamarca',
      'America/Argentina/Cordoba',
      'America/Argentina/Jujuy',
      'America/Argentina/La_Rioja',
      'America/Argentina/Mendoza',
      'America/Argentina/Rio_Gallegos',
      'America/Argentina/Salta',
      'America/Argentina/San_Juan',
      'America/Argentina/San_Luis',
      'America/Argentina/Tucuman',
      'America/Argentina/Ushuaia',
    ],
  },
  {
    name: 'Armenia',
    code: 'AM',
    currency: 'AMD',
    nativeName: 'Հայաստան',
    timezones: ['Asia/Yerevan'],
  },
  {
    name: 'Aruba',
    code: 'AW',
    currency: 'AWG',
    nativeName: 'Aruba',
    timezones: ['America/Aruba'],
  },
  {
    name: 'Australia',
    code: 'AU',
    currency: 'AUD',
    nativeName: 'Australia',
    timezones: [
      'Antarctica/Macquarie',
      'Australia/Adelaide',
      'Australia/Brisbane',
      'Australia/Broken_Hill',
      'Australia/Currie',
      'Australia/Darwin',
      'Australia/Eucla',
      'Australia/Hobart',
      'Australia/Lindeman',
      'Australia/Lord_Howe',
      'Australia/Melbourne',
      'Australia/Perth',
      'Australia/Sydney',
    ],
  },
  {
    name: 'Austria',
    code: 'AT',
    currency: 'EUR',
    nativeName: 'Österreich',
    timezones: ['Europe/Vienna'],
  },
  {
    name: 'Azerbaijan',
    code: 'AZ',
    currency: 'AZN',
    nativeName: 'Azərbaycan',
    timezones: ['Asia/Baku'],
  },
  {
    name: 'Bahrain',
    code: 'BH',
    currency: 'BHD',
    nativeName: '‏البحرين',
    timezones: ['Asia/Bahrain'],
  },
  {
    name: 'Bangladesh',
    code: 'BD',
    currency: 'BDT',
    nativeName: 'Bangladesh',
    timezones: ['Asia/Dhaka'],
  },
  {
    name: 'Barbados',
    code: 'BB',
    currency: 'BBD',
    nativeName: 'Barbados',
    timezones: ['America/Barbados'],
  },
  {
    name: 'Belarus',
    code: 'BY',
    currency: 'BYN',
    nativeName: 'Белару́сь',
    timezones: ['Europe/Minsk'],
  },
  {
    name: 'Belgium',
    code: 'BE',
    currency: 'EUR',
    nativeName: 'België',
    timezones: ['Europe/Brussels'],
  },
  {
    name: 'Belize',
    code: 'BZ',
    currency: 'BZD',
    nativeName: 'Belize',
    timezones: ['America/Belize'],
  },
  {
    name: 'Benin',
    code: 'BJ',
    currency: 'XOF',
    nativeName: 'Bénin',
    timezones: ['Africa/Porto-Novo'],
  },
  {
    name: 'Bermuda',
    code: 'BM',
    currency: 'BMD',
    nativeName: 'Bermuda',
    timezones: ['Atlantic/Bermuda'],
  },
  {
    name: 'Bhutan',
    code: 'BT',
    currency: 'BTN',
    nativeName: 'ʼbrug-yul',
    timezones: ['Asia/Thimphu'],
  },
  {
    name: 'Bolivia',
    code: 'BO',
    currency: 'BOB',
    nativeName: 'Bolivia',
    timezones: ['America/La_Paz'],
  },
  {
    name: 'Bonaire, Sint Eustatius and Saba',
    code: 'BQ',
    currency: 'USD',
    nativeName: 'Caribisch Nederland',
    timezones: ['America/Anguilla'],
  },
  {
    name: 'Bosnia and Herzegovina',
    code: 'BA',
    currency: 'BAM',
    nativeName: 'Bosna i Hercegovina',
    timezones: ['Europe/Sarajevo'],
  },
  {
    name: 'Botswana',
    code: 'BW',
    currency: 'BWP',
    nativeName: 'Botswana',
    timezones: ['Africa/Gaborone'],
  },
  {
    name: 'Bouvet Island',
    code: 'BV',
    currency: 'NOK',
    nativeName: 'Bouvetøya',
    timezones: ['Europe/Oslo'],
  },
  {
    name: 'Brazil',
    code: 'BR',
    currency: 'BRL',
    nativeName: 'Brasil',
    timezones: [
      'America/Araguaina',
      'America/Bahia',
      'America/Belem',
      'America/Boa_Vista',
      'America/Campo_Grande',
      'America/Cuiaba',
      'America/Eirunepe',
      'America/Fortaleza',
      'America/Maceio',
      'America/Manaus',
      'America/Noronha',
      'America/Porto_Velho',
      'America/Recife',
      'America/Rio_Branco',
      'America/Santarem',
      'America/Sao_Paulo',
    ],
  },
  {
    name: 'British Indian Ocean Territory',
    code: 'IO',
    currency: 'USD',
    nativeName: 'British Indian Ocean Territory',
    timezones: ['Indian/Chagos'],
  },
  {
    name: 'Brunei',
    code: 'BN',
    currency: 'BND',
    nativeName: 'Negara Brunei Darussalam',
    timezones: ['Asia/Brunei'],
  },
  {
    name: 'Bulgaria',
    code: 'BG',
    currency: 'BGN',
    nativeName: 'България',
    timezones: ['Europe/Sofia'],
  },
  {
    name: 'Burkina Faso',
    code: 'BF',
    currency: 'XOF',
    nativeName: 'Burkina Faso',
    timezones: ['Africa/Ouagadougou'],
  },
  {
    name: 'Burundi',
    code: 'BI',
    currency: 'BIF',
    nativeName: 'Burundi',
    timezones: ['Africa/Bujumbura'],
  },
  {
    name: 'Cambodia',
    code: 'KH',
    currency: 'KHR',
    nativeName: 'Kâmpŭchéa',
    timezones: ['Asia/Phnom_Penh'],
  },
  {
    name: 'Cameroon',
    code: 'CM',
    currency: 'XAF',
    nativeName: 'Cameroon',
    timezones: ['Africa/Douala'],
  },
  {
    name: 'Canada',
    code: 'CA',
    currency: 'CAD',
    nativeName: 'Canada',
    timezones: [
      'America/Atikokan',
      'America/Blanc-Sablon',
      'America/Cambridge_Bay',
      'America/Creston',
      'America/Dawson',
      'America/Dawson_Creek',
      'America/Edmonton',
      'America/Fort_Nelson',
      'America/Glace_Bay',
      'America/Goose_Bay',
      'America/Halifax',
      'America/Inuvik',
      'America/Iqaluit',
      'America/Moncton',
      'America/Nipigon',
      'America/Pangnirtung',
      'America/Rainy_River',
      'America/Rankin_Inlet',
      'America/Regina',
      'America/Resolute',
      'America/St_Johns',
      'America/Swift_Current',
      'America/Thunder_Bay',
      'America/Toronto',
      'America/Vancouver',
      'America/Whitehorse',
      'America/Winnipeg',
      'America/Yellowknife',
    ],
  },
  {
    name: 'Cape Verde',
    code: 'CV',
    currency: 'CVE',
    nativeName: 'Cabo Verde',
    timezones: ['Atlantic/Cape_Verde'],
  },
  {
    name: 'Cayman Islands',
    code: 'KY',
    currency: 'KYD',
    nativeName: 'Cayman Islands',
    timezones: ['America/Cayman'],
  },
  {
    name: 'Central African Republic',
    code: 'CF',
    currency: 'XAF',
    nativeName: 'Ködörösêse tî Bêafrîka',
    timezones: ['Africa/Bangui'],
  },
  {
    name: 'Chad',
    code: 'TD',
    currency: 'XAF',
    nativeName: 'Tchad',
    timezones: ['Africa/Ndjamena'],
  },
  {
    name: 'Chile',
    code: 'CL',
    currency: 'CLP',
    nativeName: 'Chile',
    timezones: ['America/Punta_Arenas', 'America/Santiago', 'Pacific/Easter'],
  },
  {
    name: 'China',
    code: 'CN',
    currency: 'CNY',
    nativeName: '中国',
    timezones: ['Asia/Shanghai', 'Asia/Urumqi'],
  },
  {
    name: 'Christmas Island',
    code: 'CX',
    currency: 'AUD',
    nativeName: 'Christmas Island',
    timezones: ['Indian/Christmas'],
  },
  {
    name: 'Cocos (Keeling) Islands',
    code: 'CC',
    currency: 'AUD',
    nativeName: 'Cocos (Keeling) Islands',
    timezones: ['Indian/Cocos'],
  },
  {
    name: 'Colombia',
    code: 'CO',
    currency: 'COP',
    nativeName: 'Colombia',
    timezones: ['America/Bogota'],
  },
  {
    name: 'Comoros',
    code: 'KM',
    currency: 'KMF',
    nativeName: 'Komori',
    timezones: ['Indian/Comoro'],
  },
  {
    name: 'Congo',
    code: 'CG',
    currency: 'XAF',
    nativeName: 'République du Congo',
    timezones: ['Africa/Brazzaville'],
  },
  {
    name: 'Cook Islands',
    code: 'CK',
    currency: 'NZD',
    nativeName: 'Cook Islands',
    timezones: ['Pacific/Rarotonga'],
  },
  {
    name: 'Costa Rica',
    code: 'CR',
    currency: 'CRC',
    nativeName: 'Costa Rica',
    timezones: ['America/Costa_Rica'],
  },
  {
    name: "Cote D'Ivoire (Ivory Coast)",
    code: 'CI',
    currency: 'XOF',
    nativeName: null,
    timezones: ['Africa/Abidjan'],
  },
  {
    name: 'Croatia',
    code: 'HR',
    currency: 'HRK',
    nativeName: 'Hrvatska',
    timezones: ['Europe/Zagreb'],
  },
  {
    name: 'Cuba',
    code: 'CU',
    currency: 'CUP',
    nativeName: 'Cuba',
    timezones: ['America/Havana'],
  },
  {
    name: 'Curaçao',
    code: 'CW',
    currency: 'ANG',
    nativeName: 'Curaçao',
    timezones: ['America/Curacao'],
  },
  {
    name: 'Cyprus',
    code: 'CY',
    currency: 'EUR',
    nativeName: 'Κύπρος',
    timezones: ['Asia/Famagusta', 'Asia/Nicosia'],
  },
  {
    name: 'Czech Republic',
    code: 'CZ',
    currency: 'CZK',
    nativeName: 'Česká republika',
    timezones: null,
  },
  {
    name: 'Democratic Republic of the Congo',
    code: 'CD',
    currency: 'CDF',
    nativeName: 'République démocratique du Congo',
    timezones: ['Africa/Kinshasa', 'Africa/Lubumbashi'],
  },
  {
    name: 'Denmark',
    code: 'DK',
    currency: 'DKK',
    nativeName: 'Danmark',
    timezones: ['Europe/Copenhagen'],
  },
  {
    name: 'Djibouti',
    code: 'DJ',
    currency: 'DJF',
    nativeName: 'Djibouti',
    timezones: ['Africa/Djibouti'],
  },
  {
    name: 'Dominica',
    code: 'DM',
    currency: 'XCD',
    nativeName: 'Dominica',
    timezones: ['America/Dominica'],
  },
  {
    name: 'Dominican Republic',
    code: 'DO',
    currency: 'DOP',
    nativeName: 'República Dominicana',
    timezones: ['America/Santo_Domingo'],
  },
  {
    name: 'East Timor',
    code: 'TL',
    currency: 'USD',
    nativeName: 'Timor-Leste',
    timezones: ['Asia/Dili'],
  },
  {
    name: 'Ecuador',
    code: 'EC',
    currency: 'USD',
    nativeName: 'Ecuador',
    timezones: ['America/Guayaquil', 'Pacific/Galapagos'],
  },
  {
    name: 'Egypt',
    code: 'EG',
    currency: 'EGP',
    nativeName: 'مصر‎',
    timezones: ['Africa/Cairo'],
  },
  {
    name: 'El Salvador',
    code: 'SV',
    currency: 'USD',
    nativeName: 'El Salvador',
    timezones: ['America/El_Salvador'],
  },
  {
    name: 'Equatorial Guinea',
    code: 'GQ',
    currency: 'XAF',
    nativeName: 'Guinea Ecuatorial',
    timezones: ['Africa/Malabo'],
  },
  {
    name: 'Eritrea',
    code: 'ER',
    currency: 'ERN',
    nativeName: 'ኤርትራ',
    timezones: ['Africa/Asmara'],
  },
  {
    name: 'Estonia',
    code: 'EE',
    currency: 'EUR',
    nativeName: 'Eesti',
    timezones: ['Europe/Tallinn'],
  },
  {
    name: 'Ethiopia',
    code: 'ET',
    currency: 'ETB',
    nativeName: 'ኢትዮጵያ',
    timezones: ['Africa/Addis_Ababa'],
  },
  {
    name: 'Falkland Islands',
    code: 'FK',
    currency: 'FKP',
    nativeName: 'Falkland Islands',
    timezones: ['Atlantic/Stanley'],
  },
  {
    name: 'Faroe Islands',
    code: 'FO',
    currency: 'DKK',
    nativeName: 'Føroyar',
    timezones: ['Atlantic/Faroe'],
  },
  {
    name: 'Fiji Islands',
    code: 'FJ',
    currency: 'FJD',
    nativeName: 'Fiji',
    timezones: ['Pacific/Fiji'],
  },
  {
    name: 'Finland',
    code: 'FI',
    currency: 'EUR',
    nativeName: 'Suomi',
    timezones: ['Europe/Helsinki'],
  },
  {
    name: 'France',
    code: 'FR',
    currency: 'EUR',
    nativeName: 'France',
    timezones: ['Europe/Paris'],
  },
  {
    name: 'French Guiana',
    code: 'GF',
    currency: 'EUR',
    nativeName: 'Guyane française',
    timezones: ['America/Cayenne'],
  },
  {
    name: 'French Polynesia',
    code: 'PF',
    currency: 'XPF',
    nativeName: 'Polynésie française',
    timezones: ['Pacific/Gambier', 'Pacific/Marquesas', 'Pacific/Tahiti'],
  },
  {
    name: 'French Southern Territories',
    code: 'TF',
    currency: 'EUR',
    nativeName: 'Territoire des Terres australes et antarctiques fr',
    timezones: ['Indian/Kerguelen'],
  },
  {
    name: 'Gabon',
    code: 'GA',
    currency: 'XAF',
    nativeName: 'Gabon',
    timezones: ['Africa/Libreville'],
  },
  {
    name: 'Gambia The',
    code: 'GM',
    currency: 'GMD',
    nativeName: 'Gambia',
    timezones: ['Africa/Banjul'],
  },
  {
    name: 'Georgia',
    code: 'GE',
    currency: 'GEL',
    nativeName: 'საქართველო',
    timezones: ['Asia/Tbilisi'],
  },
  {
    name: 'Germany',
    code: 'DE',
    currency: 'EUR',
    nativeName: 'Deutschland',
    timezones: ['Europe/Berlin', 'Europe/Busingen'],
  },
  {
    name: 'Ghana',
    code: 'GH',
    currency: 'GHS',
    nativeName: 'Ghana',
    timezones: ['Africa/Accra'],
  },
  {
    name: 'Gibraltar',
    code: 'GI',
    currency: 'GIP',
    nativeName: 'Gibraltar',
    timezones: ['Europe/Gibraltar'],
  },
  {
    name: 'Greece',
    code: 'GR',
    currency: 'EUR',
    nativeName: 'Ελλάδα',
    timezones: ['Europe/Athens'],
  },
  {
    name: 'Greenland',
    code: 'GL',
    currency: 'DKK',
    nativeName: 'Kalaallit Nunaat',
    timezones: ['America/Danmarkshavn', 'America/Nuuk', 'America/Scoresbysund', 'America/Thule'],
  },
  {
    name: 'Grenada',
    code: 'GD',
    currency: 'XCD',
    nativeName: 'Grenada',
    timezones: ['America/Grenada'],
  },
  {
    name: 'Guadeloupe',
    code: 'GP',
    currency: 'EUR',
    nativeName: 'Guadeloupe',
    timezones: ['America/Guadeloupe'],
  },
  {
    name: 'Guam',
    code: 'GU',
    currency: 'USD',
    nativeName: 'Guam',
    timezones: ['Pacific/Guam'],
  },
  {
    name: 'Guatemala',
    code: 'GT',
    currency: 'GTQ',
    nativeName: 'Guatemala',
    timezones: ['America/Guatemala'],
  },
  {
    name: 'Guernsey and Alderney',
    code: 'GG',
    currency: 'GBP',
    nativeName: 'Guernsey',
    timezones: ['Europe/Guernsey'],
  },
  {
    name: 'Guinea',
    code: 'GN',
    currency: 'GNF',
    nativeName: 'Guinée',
    timezones: ['Africa/Conakry'],
  },
  {
    name: 'Guinea-Bissau',
    code: 'GW',
    currency: 'XOF',
    nativeName: 'Guiné-Bissau',
    timezones: ['Africa/Bissau'],
  },
  {
    name: 'Guyana',
    code: 'GY',
    currency: 'GYD',
    nativeName: 'Guyana',
    timezones: ['America/Guyana'],
  },
  {
    name: 'Haiti',
    code: 'HT',
    currency: 'HTG',
    nativeName: 'Haïti',
    timezones: ['America/Port-au-Prince'],
  },
  {
    name: 'Heard Island and McDonald Islands',
    code: 'HM',
    currency: 'AUD',
    nativeName: 'Heard Island and McDonald Islands',
    timezones: ['Indian/Kerguelen'],
  },
  {
    name: 'Honduras',
    code: 'HN',
    currency: 'HNL',
    nativeName: 'Honduras',
    timezones: ['America/Tegucigalpa'],
  },
  {
    name: 'Hong Kong S.A.R.',
    code: 'HK',
    currency: 'HKD',
    nativeName: '香港',
    timezones: ['Asia/Hong_Kong'],
  },
  {
    name: 'Hungary',
    code: 'HU',
    currency: 'HUF',
    nativeName: 'Magyarország',
    timezones: ['Europe/Budapest'],
  },
  {
    name: 'Iceland',
    code: 'IS',
    currency: 'ISK',
    nativeName: 'Ísland',
    timezones: ['Atlantic/Reykjavik'],
  },
  {
    name: 'India',
    code: 'IN',
    currency: 'INR',
    nativeName: 'भारत',
    timezones: ['Asia/Kolkata'],
  },
  {
    name: 'Indonesia',
    code: 'ID',
    currency: 'IDR',
    nativeName: 'Indonesia',
    timezones: ['Asia/Jakarta', 'Asia/Jayapura', 'Asia/Makassar', 'Asia/Pontianak'],
  },
  {
    name: 'Iran',
    code: 'IR',
    currency: 'IRR',
    nativeName: 'ایران',
    timezones: ['Asia/Tehran'],
  },
  {
    name: 'Iraq',
    code: 'IQ',
    currency: 'IQD',
    nativeName: 'العراق',
    timezones: ['Asia/Baghdad'],
  },
  {
    name: 'Ireland',
    code: 'IE',
    currency: 'EUR',
    nativeName: 'Éire',
    timezones: ['Europe/Dublin'],
  },
  {
    name: 'Israel',
    code: 'IL',
    currency: 'ILS',
    nativeName: 'יִשְׂרָאֵל',
    timezones: ['Asia/Jerusalem'],
  },
  {
    name: 'Italy',
    code: 'IT',
    currency: 'EUR',
    nativeName: 'Italia',
    timezones: ['Europe/Rome'],
  },
  {
    name: 'Jamaica',
    code: 'JM',
    currency: 'JMD',
    nativeName: 'Jamaica',
    timezones: ['America/Jamaica'],
  },
  {
    name: 'Japan',
    code: 'JP',
    currency: 'JPY',
    nativeName: '日本',
    timezones: ['Asia/Tokyo'],
  },
  {
    name: 'Jersey',
    code: 'JE',
    currency: 'GBP',
    nativeName: 'Jersey',
    timezones: ['Europe/Jersey'],
  },
  {
    name: 'Jordan',
    code: 'JO',
    currency: 'JOD',
    nativeName: 'الأردن',
    timezones: ['Asia/Amman'],
  },
  {
    name: 'Kazakhstan',
    code: 'KZ',
    currency: 'KZT',
    nativeName: 'Қазақстан',
    timezones: [
      'Asia/Almaty',
      'Asia/Aqtau',
      'Asia/Aqtobe',
      'Asia/Atyrau',
      'Asia/Oral',
      'Asia/Qostanay',
      'Asia/Qyzylorda',
    ],
  },
  {
    name: 'Kenya',
    code: 'KE',
    currency: 'KES',
    nativeName: 'Kenya',
    timezones: ['Africa/Nairobi'],
  },
  {
    name: 'Kiribati',
    code: 'KI',
    currency: 'AUD',
    nativeName: 'Kiribati',
    timezones: ['Pacific/Enderbury', 'Pacific/Kiritimati', 'Pacific/Tarawa'],
  },
  {
    name: 'Kosovo',
    code: 'XK',
    currency: 'EUR',
    nativeName: 'Republika e Kosovës',
    timezones: ['Europe/Belgrade'],
  },
  {
    name: 'Kuwait',
    code: 'KW',
    currency: 'KWD',
    nativeName: 'الكويت',
    timezones: ['Asia/Kuwait'],
  },
  {
    name: 'Kyrgyzstan',
    code: 'KG',
    currency: 'KGS',
    nativeName: 'Кыргызстан',
    timezones: ['Asia/Bishkek'],
  },
  {
    name: 'Laos',
    code: 'LA',
    currency: 'LAK',
    nativeName: 'ສປປລາວ',
    timezones: ['Asia/Vientiane'],
  },
  {
    name: 'Latvia',
    code: 'LV',
    currency: 'EUR',
    nativeName: 'Latvija',
    timezones: ['Europe/Riga'],
  },
  {
    name: 'Lebanon',
    code: 'LB',
    currency: 'LBP',
    nativeName: 'لبنان',
    timezones: ['Asia/Beirut'],
  },
  {
    name: 'Lesotho',
    code: 'LS',
    currency: 'LSL',
    nativeName: 'Lesotho',
    timezones: ['Africa/Maseru'],
  },
  {
    name: 'Liberia',
    code: 'LR',
    currency: 'LRD',
    nativeName: 'Liberia',
    timezones: ['Africa/Monrovia'],
  },
  {
    name: 'Libya',
    code: 'LY',
    currency: 'LYD',
    nativeName: '‏ليبيا',
    timezones: ['Africa/Tripoli'],
  },
  {
    name: 'Liechtenstein',
    code: 'LI',
    currency: 'CHF',
    nativeName: 'Liechtenstein',
    timezones: ['Europe/Vaduz'],
  },
  {
    name: 'Lithuania',
    code: 'LT',
    currency: 'EUR',
    nativeName: 'Lietuva',
    timezones: ['Europe/Vilnius'],
  },
  {
    name: 'Luxembourg',
    code: 'LU',
    currency: 'EUR',
    nativeName: 'Luxembourg',
    timezones: ['Europe/Luxembourg'],
  },
  {
    name: 'Macau S.A.R.',
    code: 'MO',
    currency: 'MOP',
    nativeName: '澳門',
    timezones: ['Asia/Macau'],
  },
  {
    name: 'Madagascar',
    code: 'MG',
    currency: 'MGA',
    nativeName: 'Madagasikara',
    timezones: ['Indian/Antananarivo'],
  },
  {
    name: 'Malawi',
    code: 'MW',
    currency: 'MWK',
    nativeName: 'Malawi',
    timezones: ['Africa/Blantyre'],
  },
  {
    name: 'Malaysia',
    code: 'MY',
    currency: 'MYR',
    nativeName: 'Malaysia',
    timezones: ['Asia/Kuala_Lumpur', 'Asia/Kuching'],
  },
  {
    name: 'Maldives',
    code: 'MV',
    currency: 'MVR',
    nativeName: 'Maldives',
    timezones: ['Indian/Maldives'],
  },
  {
    name: 'Mali',
    code: 'ML',
    currency: 'XOF',
    nativeName: 'Mali',
    timezones: ['Africa/Bamako'],
  },
  {
    name: 'Malta',
    code: 'MT',
    currency: 'EUR',
    nativeName: 'Malta',
    timezones: ['Europe/Malta'],
  },
  {
    name: 'Man (Isle of)',
    code: 'IM',
    currency: 'GBP',
    nativeName: 'Isle of Man',
    timezones: ['Europe/Isle_of_Man'],
  },
  {
    name: 'Marshall Islands',
    code: 'MH',
    currency: 'USD',
    nativeName: 'M̧ajeļ',
    timezones: ['Pacific/Kwajalein', 'Pacific/Majuro'],
  },
  {
    name: 'Martinique',
    code: 'MQ',
    currency: 'EUR',
    nativeName: 'Martinique',
    timezones: ['America/Martinique'],
  },
  {
    name: 'Mauritania',
    code: 'MR',
    currency: 'MRO',
    nativeName: 'موريتانيا',
    timezones: ['Africa/Nouakchott'],
  },
  {
    name: 'Mauritius',
    code: 'MU',
    currency: 'MUR',
    nativeName: 'Maurice',
    timezones: ['Indian/Mauritius'],
  },
  {
    name: 'Mayotte',
    code: 'YT',
    currency: 'EUR',
    nativeName: 'Mayotte',
    timezones: ['Indian/Mayotte'],
  },
  {
    name: 'Mexico',
    code: 'MX',
    currency: 'MXN',
    nativeName: 'México',
    timezones: [
      'America/Bahia_Banderas',
      'America/Cancun',
      'America/Chihuahua',
      'America/Hermosillo',
      'America/Matamoros',
      'America/Mazatlan',
      'America/Merida',
      'America/Mexico_City',
      'America/Monterrey',
      'America/Ojinaga',
      'America/Tijuana',
    ],
  },
  {
    name: 'Micronesia',
    code: 'FM',
    currency: 'USD',
    nativeName: 'Micronesia',
    timezones: ['Pacific/Chuuk', 'Pacific/Kosrae', 'Pacific/Pohnpei'],
  },
  {
    name: 'Moldova',
    code: 'MD',
    currency: 'MDL',
    nativeName: 'Moldova',
    timezones: ['Europe/Chisinau'],
  },
  {
    name: 'Monaco',
    code: 'MC',
    currency: 'EUR',
    nativeName: 'Monaco',
    timezones: ['Europe/Monaco'],
  },
  {
    name: 'Mongolia',
    code: 'MN',
    currency: 'MNT',
    nativeName: 'Монгол улс',
    timezones: ['Asia/Choibalsan', 'Asia/Hovd', 'Asia/Ulaanbaatar'],
  },
  {
    name: 'Montenegro',
    code: 'ME',
    currency: 'EUR',
    nativeName: 'Црна Гора',
    timezones: ['Europe/Podgorica'],
  },
  {
    name: 'Montserrat',
    code: 'MS',
    currency: 'XCD',
    nativeName: 'Montserrat',
    timezones: ['America/Montserrat'],
  },
  {
    name: 'Morocco',
    code: 'MA',
    currency: 'MAD',
    nativeName: 'المغرب',
    timezones: ['Africa/Casablanca'],
  },
  {
    name: 'Mozambique',
    code: 'MZ',
    currency: 'MZN',
    nativeName: 'Moçambique',
    timezones: ['Africa/Maputo'],
  },
  {
    name: 'Myanmar',
    code: 'MM',
    currency: 'MMK',
    nativeName: 'မြန်မာ',
    timezones: ['Asia/Yangon'],
  },
  {
    name: 'Namibia',
    code: 'NA',
    currency: 'NAD',
    nativeName: 'Namibia',
    timezones: ['Africa/Windhoek'],
  },
  {
    name: 'Nauru',
    code: 'NR',
    currency: 'AUD',
    nativeName: 'Nauru',
    timezones: ['Pacific/Nauru'],
  },
  {
    name: 'Nepal',
    code: 'NP',
    currency: 'NPR',
    nativeName: 'नपल',
    timezones: ['Asia/Kathmandu'],
  },
  {
    name: 'Netherlands',
    code: 'NL',
    currency: 'EUR',
    nativeName: 'Nederland',
    timezones: ['Europe/Amsterdam'],
  },
  {
    name: 'New Caledonia',
    code: 'NC',
    currency: 'XPF',
    nativeName: 'Nouvelle-Calédonie',
    timezones: ['Pacific/Noumea'],
  },
  {
    name: 'New Zealand',
    code: 'NZ',
    currency: 'NZD',
    nativeName: 'New Zealand',
    timezones: ['Pacific/Auckland', 'Pacific/Chatham'],
  },
  {
    name: 'Nicaragua',
    code: 'NI',
    currency: 'NIO',
    nativeName: 'Nicaragua',
    timezones: ['America/Managua'],
  },
  {
    name: 'Niger',
    code: 'NE',
    currency: 'XOF',
    nativeName: 'Niger',
    timezones: ['Africa/Niamey'],
  },
  {
    name: 'Nigeria',
    code: 'NG',
    currency: 'NGN',
    nativeName: 'Nigeria',
    timezones: ['Africa/Lagos'],
  },
  {
    name: 'Niue',
    code: 'NU',
    currency: 'NZD',
    nativeName: 'Niuē',
    timezones: ['Pacific/Niue'],
  },
  {
    name: 'Norfolk Island',
    code: 'NF',
    currency: 'AUD',
    nativeName: 'Norfolk Island',
    timezones: ['Pacific/Norfolk'],
  },
  {
    name: 'North Korea',
    code: 'KP',
    currency: 'KPW',
    nativeName: '북한',
    timezones: ['Asia/Pyongyang'],
  },
  {
    name: 'North Macedonia',
    code: 'MK',
    currency: 'MKD',
    nativeName: 'Северна Македонија',
    timezones: ['Europe/Skopje'],
  },
  {
    name: 'Northern Mariana Islands',
    code: 'MP',
    currency: 'USD',
    nativeName: 'Northern Mariana Islands',
    timezones: ['Pacific/Saipan'],
  },
  {
    name: 'Norway',
    code: 'NO',
    currency: 'NOK',
    nativeName: 'Norge',
    timezones: ['Europe/Oslo'],
  },
  {
    name: 'Oman',
    code: 'OM',
    currency: 'OMR',
    nativeName: 'عمان',
    timezones: ['Asia/Muscat'],
  },
  {
    name: 'Pakistan',
    code: 'PK',
    currency: 'PKR',
    nativeName: 'Pakistan',
    timezones: ['Asia/Karachi'],
  },
  {
    name: 'Palau',
    code: 'PW',
    currency: 'USD',
    nativeName: 'Palau',
    timezones: ['Pacific/Palau'],
  },
  {
    name: 'Palestinian Territory Occupied',
    code: 'PS',
    currency: 'ILS',
    nativeName: 'فلسطين',
    timezones: ['Asia/Gaza', 'Asia/Hebron'],
  },
  {
    name: 'Panama',
    code: 'PA',
    currency: 'PAB',
    nativeName: 'Panamá',
    timezones: ['America/Panama'],
  },
  {
    name: 'Papua new Guinea',
    code: 'PG',
    currency: 'PGK',
    nativeName: 'Papua Niugini',
    timezones: ['Pacific/Bougainville', 'Pacific/Port_Moresby'],
  },
  {
    name: 'Paraguay',
    code: 'PY',
    currency: 'PYG',
    nativeName: 'Paraguay',
    timezones: ['America/Asuncion'],
  },
  {
    name: 'Peru',
    code: 'PE',
    currency: 'PEN',
    nativeName: 'Perú',
    timezones: ['America/Lima'],
  },
  {
    name: 'Philippines',
    code: 'PH',
    currency: 'PHP',
    nativeName: 'Pilipinas',
    timezones: ['Asia/Manila'],
  },
  {
    name: 'Pitcairn Island',
    code: 'PN',
    currency: 'NZD',
    nativeName: 'Pitcairn Islands',
    timezones: ['Pacific/Pitcairn'],
  },
  {
    name: 'Poland',
    code: 'PL',
    currency: 'PLN',
    nativeName: 'Polska',
    timezones: ['Europe/Warsaw'],
  },
  {
    name: 'Portugal',
    code: 'PT',
    currency: 'EUR',
    nativeName: 'Portugal',
    timezones: ['Atlantic/Azores', 'Atlantic/Madeira', 'Europe/Lisbon'],
  },
  {
    name: 'Puerto Rico',
    code: 'PR',
    currency: 'USD',
    nativeName: 'Puerto Rico',
    timezones: ['America/Puerto_Rico'],
  },
  {
    name: 'Qatar',
    code: 'QA',
    currency: 'QAR',
    nativeName: 'قطر',
    timezones: ['Asia/Qatar'],
  },
  {
    name: 'Reunion',
    code: 'RE',
    currency: 'EUR',
    nativeName: 'La Réunion',
    timezones: ['Indian/Reunion'],
  },
  {
    name: 'Romania',
    code: 'RO',
    currency: 'RON',
    nativeName: 'România',
    timezones: ['Europe/Bucharest'],
  },
  {
    name: 'Russia',
    code: 'RU',
    currency: 'RUB',
    nativeName: 'Россия',
    timezones: [
      'Asia/Anadyr',
      'Asia/Barnaul',
      'Asia/Chita',
      'Asia/Irkutsk',
      'Asia/Kamchatka',
      'Asia/Khandyga',
      'Asia/Krasnoyarsk',
      'Asia/Magadan',
      'Asia/Novokuznetsk',
      'Asia/Novosibirsk',
      'Asia/Omsk',
      'Asia/Sakhalin',
      'Asia/Srednekolymsk',
      'Asia/Tomsk',
      'Asia/Ust-Nera',
      'Asia/Vladivostok',
      'Asia/Yakutsk',
      'Asia/Yekaterinburg',
      'Europe/Astrakhan',
      'Europe/Kaliningrad',
      'Europe/Kirov',
      'Europe/Moscow',
      'Europe/Samara',
      'Europe/Saratov',
      'Europe/Ulyanovsk',
      'Europe/Volgograd',
    ],
  },
  {
    name: 'Rwanda',
    code: 'RW',
    currency: 'RWF',
    nativeName: 'Rwanda',
    timezones: ['Africa/Kigali'],
  },
  {
    name: 'Saint Helena',
    code: 'SH',
    currency: 'SHP',
    nativeName: 'Saint Helena',
    timezones: ['Atlantic/St_Helena'],
  },
  {
    name: 'Saint Kitts And Nevis',
    code: 'KN',
    currency: 'XCD',
    nativeName: 'Saint Kitts and Nevis',
    timezones: ['America/St_Kitts'],
  },
  {
    name: 'Saint Lucia',
    code: 'LC',
    currency: 'XCD',
    nativeName: 'Saint Lucia',
    timezones: ['America/St_Lucia'],
  },
  {
    name: 'Saint Pierre and Miquelon',
    code: 'PM',
    currency: 'EUR',
    nativeName: 'Saint-Pierre-et-Miquelon',
    timezones: ['America/Miquelon'],
  },
  {
    name: 'Saint Vincent And The Grenadines',
    code: 'VC',
    currency: 'XCD',
    nativeName: 'Saint Vincent and the Grenadines',
    timezones: ['America/St_Vincent'],
  },
  {
    name: 'Saint-Barthelemy',
    code: 'BL',
    currency: 'EUR',
    nativeName: 'Saint-Barthélemy',
    timezones: ['America/St_Barthelemy'],
  },
  {
    name: 'Saint-Martin (French part)',
    code: 'MF',
    currency: 'EUR',
    nativeName: 'Saint-Martin',
    timezones: ['America/Marigot'],
  },
  {
    name: 'Samoa',
    code: 'WS',
    currency: 'WST',
    nativeName: 'Samoa',
    timezones: ['Pacific/Apia'],
  },
  {
    name: 'San Marino',
    code: 'SM',
    currency: 'EUR',
    nativeName: 'San Marino',
    timezones: ['Europe/San_Marino'],
  },
  {
    name: 'Sao Tome and Principe',
    code: 'ST',
    currency: 'STD',
    nativeName: 'São Tomé e Príncipe',
    timezones: ['Africa/Sao_Tome'],
  },
  {
    name: 'Saudi Arabia',
    code: 'SA',
    currency: 'SAR',
    nativeName: 'المملكة العربية السعودية',
    timezones: ['Asia/Riyadh'],
  },
  {
    name: 'Senegal',
    code: 'SN',
    currency: 'XOF',
    nativeName: 'Sénégal',
    timezones: ['Africa/Dakar'],
  },
  {
    name: 'Serbia',
    code: 'RS',
    currency: 'RSD',
    nativeName: 'Србија',
    timezones: ['Europe/Belgrade'],
  },
  {
    name: 'Seychelles',
    code: 'SC',
    currency: 'SCR',
    nativeName: 'Seychelles',
    timezones: ['Indian/Mahe'],
  },
  {
    name: 'Sierra Leone',
    code: 'SL',
    currency: 'SLL',
    nativeName: 'Sierra Leone',
    timezones: ['Africa/Freetown'],
  },
  {
    name: 'Singapore',
    code: 'SG',
    currency: 'SGD',
    nativeName: 'Singapore',
    timezones: ['Asia/Singapore'],
  },
  {
    name: 'Sint Maarten (Dutch part)',
    code: 'SX',
    currency: 'ANG',
    nativeName: 'Sint Maarten',
    timezones: ['America/Anguilla'],
  },
  {
    name: 'Slovakia',
    code: 'SK',
    currency: 'EUR',
    nativeName: 'Slovensko',
    timezones: ['Europe/Bratislava'],
  },
  {
    name: 'Slovenia',
    code: 'SI',
    currency: 'EUR',
    nativeName: 'Slovenija',
    timezones: ['Europe/Ljubljana'],
  },
  {
    name: 'Solomon Islands',
    code: 'SB',
    currency: 'SBD',
    nativeName: 'Solomon Islands',
    timezones: ['Pacific/Guadalcanal'],
  },
  {
    name: 'Somalia',
    code: 'SO',
    currency: 'SOS',
    nativeName: 'Soomaaliya',
    timezones: ['Africa/Mogadishu'],
  },
  {
    name: 'South Africa',
    code: 'ZA',
    currency: 'ZAR',
    nativeName: 'South Africa',
    timezones: ['Africa/Johannesburg'],
  },
  {
    name: 'South Georgia',
    code: 'GS',
    currency: 'GBP',
    nativeName: 'South Georgia',
    timezones: ['Atlantic/South_Georgia'],
  },
  {
    name: 'South Korea',
    code: 'KR',
    currency: 'KRW',
    nativeName: '대한민국',
    timezones: ['Asia/Seoul'],
  },
  {
    name: 'South Sudan',
    code: 'SS',
    currency: 'SSP',
    nativeName: 'South Sudan',
    timezones: ['Africa/Juba'],
  },
  {
    name: 'Spain',
    code: 'ES',
    currency: 'EUR',
    nativeName: 'España',
    timezones: ['Africa/Ceuta', 'Atlantic/Canary', 'Europe/Madrid'],
  },
  {
    name: 'Sri Lanka',
    code: 'LK',
    currency: 'LKR',
    nativeName: 'śrī laṃkāva',
    timezones: ['Asia/Colombo'],
  },
  {
    name: 'Sudan',
    code: 'SD',
    currency: 'SDG',
    nativeName: 'السودان',
    timezones: ['Africa/Khartoum'],
  },
  {
    name: 'Suriname',
    code: 'SR',
    currency: 'SRD',
    nativeName: 'Suriname',
    timezones: ['America/Paramaribo'],
  },
  {
    name: 'Svalbard And Jan Mayen Islands',
    code: 'SJ',
    currency: 'NOK',
    nativeName: 'Svalbard og Jan Mayen',
    timezones: ['Arctic/Longyearbyen'],
  },
  {
    name: 'Swaziland',
    code: 'SZ',
    currency: 'SZL',
    nativeName: 'Swaziland',
    timezones: ['Africa/Mbabane'],
  },
  {
    name: 'Sweden',
    code: 'SE',
    currency: 'SEK',
    nativeName: 'Sverige',
    timezones: ['Europe/Stockholm'],
  },
  {
    name: 'Switzerland',
    code: 'CH',
    currency: 'CHF',
    nativeName: 'Schweiz',
    timezones: ['Europe/Zurich'],
  },
  {
    name: 'Syria',
    code: 'SY',
    currency: 'SYP',
    nativeName: 'سوريا',
    timezones: ['Asia/Damascus'],
  },
  {
    name: 'Taiwan',
    code: 'TW',
    currency: 'TWD',
    nativeName: '臺灣',
    timezones: ['Asia/Taipei'],
  },
  {
    name: 'Tajikistan',
    code: 'TJ',
    currency: 'TJS',
    nativeName: 'Тоҷикистон',
    timezones: ['Asia/Dushanbe'],
  },
  {
    name: 'Tanzania',
    code: 'TZ',
    currency: 'TZS',
    nativeName: 'Tanzania',
    timezones: ['Africa/Dar_es_Salaam'],
  },
  {
    name: 'Thailand',
    code: 'TH',
    currency: 'THB',
    nativeName: 'ประเทศไทย',
    timezones: ['Asia/Bangkok'],
  },
  {
    name: 'The Bahamas',
    code: 'BS',
    currency: 'BSD',
    nativeName: 'Bahamas',
    timezones: ['America/Nassau'],
  },
  {
    name: 'Togo',
    code: 'TG',
    currency: 'XOF',
    nativeName: 'Togo',
    timezones: ['Africa/Lome'],
  },
  {
    name: 'Tokelau',
    code: 'TK',
    currency: 'NZD',
    nativeName: 'Tokelau',
    timezones: ['Pacific/Fakaofo'],
  },
  {
    name: 'Tonga',
    code: 'TO',
    currency: 'TOP',
    nativeName: 'Tonga',
    timezones: ['Pacific/Tongatapu'],
  },
  {
    name: 'Trinidad And Tobago',
    code: 'TT',
    currency: 'TTD',
    nativeName: 'Trinidad and Tobago',
    timezones: ['America/Port_of_Spain'],
  },
  {
    name: 'Tunisia',
    code: 'TN',
    currency: 'TND',
    nativeName: 'تونس',
    timezones: ['Africa/Tunis'],
  },
  {
    name: 'Turkey',
    code: 'TR',
    currency: 'TRY',
    nativeName: 'Türkiye',
    timezones: ['Europe/Istanbul'],
  },
  {
    name: 'Turkmenistan',
    code: 'TM',
    currency: 'TMT',
    nativeName: 'Türkmenistan',
    timezones: ['Asia/Ashgabat'],
  },
  {
    name: 'Turks And Caicos Islands',
    code: 'TC',
    currency: 'USD',
    nativeName: 'Turks and Caicos Islands',
    timezones: ['America/Grand_Turk'],
  },
  {
    name: 'Tuvalu',
    code: 'TV',
    currency: 'AUD',
    nativeName: 'Tuvalu',
    timezones: ['Pacific/Funafuti'],
  },
  {
    name: 'Uganda',
    code: 'UG',
    currency: 'UGX',
    nativeName: 'Uganda',
    timezones: ['Africa/Kampala'],
  },
  {
    name: 'Ukraine',
    code: 'UA',
    currency: 'UAH',
    nativeName: 'Україна',
    timezones: ['Europe/Kiev', 'Europe/Simferopol', 'Europe/Uzhgorod', 'Europe/Zaporozhye'],
  },
  {
    name: 'United Arab Emirates',
    code: 'AE',
    currency: 'AED',
    nativeName: 'دولة الإمارات العربية المتحدة',
    timezones: ['Asia/Dubai'],
  },
  {
    name: 'United Kingdom',
    code: 'GB',
    currency: 'GBP',
    nativeName: 'United Kingdom',
    timezones: ['Europe/London'],
  },
  {
    name: 'United States',
    code: 'US',
    currency: 'USD',
    nativeName: 'United States',
    timezones: [
      'America/Adak',
      'America/Anchorage',
      'America/Boise',
      'America/Chicago',
      'America/Denver',
      'America/Detroit',
      'America/Indiana/Indianapolis',
      'America/Indiana/Knox',
      'America/Indiana/Marengo',
      'America/Indiana/Petersburg',
      'America/Indiana/Tell_City',
      'America/Indiana/Vevay',
      'America/Indiana/Vincennes',
      'America/Indiana/Winamac',
      'America/Juneau',
      'America/Kentucky/Louisville',
      'America/Kentucky/Monticello',
      'America/Los_Angeles',
      'America/Menominee',
      'America/Metlakatla',
      'America/New_York',
      'America/Nome',
      'America/North_Dakota/Beulah',
      'America/North_Dakota/Center',
      'America/North_Dakota/New_Salem',
      'America/Phoenix',
      'America/Sitka',
      'America/Yakutat',
      'Pacific/Honolulu',
    ],
  },
  {
    name: 'United States Minor Outlying Islands',
    code: 'UM',
    currency: 'USD',
    nativeName: 'United States Minor Outlying Islands',
    timezones: ['Pacific/Midway', 'Pacific/Wake'],
  },
  {
    name: 'Uruguay',
    code: 'UY',
    currency: 'UYU',
    nativeName: 'Uruguay',
    timezones: ['America/Montevideo'],
  },
  {
    name: 'Uzbekistan',
    code: 'UZ',
    currency: 'UZS',
    nativeName: 'O‘zbekiston',
    timezones: ['Asia/Samarkand', 'Asia/Tashkent'],
  },
  {
    name: 'Vanuatu',
    code: 'VU',
    currency: 'VUV',
    nativeName: 'Vanuatu',
    timezones: ['Pacific/Efate'],
  },
  {
    name: 'Vatican City State (Holy See)',
    code: 'VA',
    currency: 'EUR',
    nativeName: 'Vaticano',
    timezones: ['Europe/Vatican'],
  },
  {
    name: 'Venezuela',
    code: 'VE',
    currency: 'VES',
    nativeName: 'Venezuela',
    timezones: ['America/Caracas'],
  },
  {
    name: 'Vietnam',
    code: 'VN',
    currency: 'VND',
    nativeName: 'Việt Nam',
    timezones: ['Asia/Ho_Chi_Minh'],
  },
  {
    name: 'Virgin Islands (British)',
    code: 'VG',
    currency: 'USD',
    nativeName: 'British Virgin Islands',
    timezones: ['America/Tortola'],
  },
  {
    name: 'Virgin Islands (US)',
    code: 'VI',
    currency: 'USD',
    nativeName: 'United States Virgin Islands',
    timezones: ['America/St_Thomas'],
  },
  {
    name: 'Wallis And Futuna Islands',
    code: 'WF',
    currency: 'XPF',
    nativeName: 'Wallis et Futuna',
    timezones: ['Pacific/Wallis'],
  },
  {
    name: 'Western Sahara',
    code: 'EH',
    currency: 'MAD',
    nativeName: 'الصحراء الغربية',
    timezones: ['Africa/El_Aaiun'],
  },
  {
    name: 'Yemen',
    code: 'YE',
    currency: 'YER',
    nativeName: 'اليَمَن',
    timezones: ['Asia/Aden'],
  },
  {
    name: 'Zambia',
    code: 'ZM',
    currency: 'ZMW',
    nativeName: 'Zambia',
    timezones: ['Africa/Lusaka'],
  },
  {
    name: 'Zimbabwe',
    code: 'ZW',
    currency: 'ZWL',
    nativeName: 'Zimbabwe',
    timezones: ['Africa/Harare'],
  },
] as const

export const CURRENCIES = Object.values(COUNTRIES).map(data => data.currency)
export const COUNTRY_CODES = Object.values(COUNTRIES).map(data => data.code)
export const TIMEZONES = Array.from(
  new Set(Object.values(COUNTRIES).flatMap(data => data.timezones))
)

export type Country = (typeof COUNTRIES)[number]
export type CountryCode = (typeof COUNTRY_CODES)[number]
export type Currency = (typeof CURRENCIES)[number]
export type TimeZone = (typeof TIMEZONES)[number] | 'UTC'
